/**
 * Server entry of the paseo-room runtime coordination plugin (preview).
 *
 * Paseo compiles this directory as-is. Only host-supplied modules may be imported —
 * `@getpaseo/plugin*` and `zod` — because the installed plugin has no `node_modules`.
 * See docs/design/runtime-coordination.md §3.3 for the components this entry registers.
 */
import type { SettingsDefinition } from '@getpaseo/plugin';
import type { PluginServerContext } from '@getpaseo/plugin/server';
import type { ZodType, output as ZodOutput } from 'zod';
import { ATTENTION_SETTINGS } from './shared/attention.js';
import { PEER_EFFORT_SETTINGS } from './shared/effort.js';
import { SEAT_CONTEXT_SETTINGS } from './shared/seat-context.js';
import { createRuntimeContext } from './server/context.js';
import { ROOM_LOCATION } from './server/generated/location.js';
import { compactMarkEnv, compactMarkOnCreate, handleSessionOpen, transformAgentCreate } from './server/hooks.js';
import { registerLifecycle } from './server/lifecycle.js';
import { registerRpcs } from './server/rpc.js';

// A hoisted function declaration on purpose: Paseo copies the bundle's exports eagerly before a
// `const` initializer would run, so a `const contribute` default export reaches it as undefined.
export default function contribute(server: PluginServerContext): () => void {
  if (ROOM_LOCATION === undefined) {
    console.error('[paseo-room-runtime] This plugin was not generated by paseo-room setup; the runtime stays inactive.');
    return () => undefined;
  }
  const runtime = createRuntimeContext(ROOM_LOCATION);
  runtime.start().catch((error: unknown) => {
    console.error(`[paseo-room-runtime] The runtime could not start: ${error instanceof Error ? error.message : String(error)}`);
  });
  const disposers = [
    server.before('agent.create', async ({ request }, context) => {
      runtime.handle.supply(context.paseo);
      await runtime.ready;
      const decorated = transformAgentCreate(request, runtime.hooks);
      return (await compactMarkOnCreate(decorated ?? request, runtime.compactMark)) ?? decorated;
    }),
    server.before('agent.session_open', async ({ request }, context) => {
      runtime.handle.supply(context.paseo);
      await runtime.ready;
      const outcome = await handleSessionOpen(request, runtime.hooks);
      if (outcome === 'ambiguous' || outcome === 'provider-mismatch') {
        console.error(`[paseo-room-runtime] Correlation for agent ${request.agentId} is ${outcome}; it will not be trusted.`);
      }
      return await compactMarkEnv(request, runtime.compactMark);
    }),
  ];
  registerRpcs(server, runtime);
  /**
   * Keeps one settings document from Paseo's host settings store: read now, then again on every
   * save. Returns the first read, or undefined when there is no store (no settings directory), in
   * which case the runtime keeps the defaults and the settings screen says so.
   */
  const watch = <Schema extends ZodType>(definition: SettingsDefinition<Schema>, adopt: (values: ZodOutput<Schema>) => void, unavailable: string): Promise<void> | undefined => {
    try {
      const settings = server.registerSettings(definition);
      const take = (state: Awaited<ReturnType<typeof settings.read>>): void => { if (state.status === 'ready') adopt(state.values); };
      const read = settings.read().then(take, () => undefined);
      const unsubscribe = settings.subscribe(take);
      disposers.push(() => { void unsubscribe(); });
      return read;
    } catch (error) {
      console.error(`[paseo-room-runtime] ${unavailable}: ${error instanceof Error ? error.message : String(error)}`);
      return undefined;
    }
  };
  runtime.attentionSettings.available = watch(ATTENTION_SETTINGS, values => { runtime.attentionSettings.current = values; },
    'Room attention settings are unavailable; defaults apply') !== undefined;
  runtime.peerEffort.available = watch(PEER_EFFORT_SETTINGS, values => {
    runtime.adoptPeerEffort(values).catch((error: unknown) => {
      console.error(`[paseo-room-runtime] The Lead tool list could not be rewritten: ${error instanceof Error ? error.message : String(error)}`);
    });
  }, 'Peer effort settings are unavailable; profile defaults apply') !== undefined;
  // A seat created or resumed at daemon start waits for this first read rather than take the defaults.
  runtime.seatContext.read = watch(SEAT_CONTEXT_SETTINGS, values => { runtime.seatContext.current = values; },
    'Seat context settings are unavailable; defaults apply') ?? Promise.resolve();
  // A notice held for a recipient's pending permission is retried once that agent can take it.
  const retryHeld = (agentId: string): Promise<number> => runtime.controller.notices.retryFor(agentId);
  const { attention } = runtime;
  disposers.push(registerLifecycle(server, runtime.handle, runtime.recovery, {
    created: async event => { await attention.onCreated(event.agent.id); },
    turnStarted: async event => { runtime.turns.turnStarted(event); await attention.onTurnStarted(event.agent.id); },
    archived: async event => { await attention.onArchived(event.agent.id, event.archivedAt); },
    turnEnded: async event => {
      await runtime.turns.turnEnded(event);
      await retryHeld(event.agent.id);
      await attention.onTurnEnded(event.agent.id, event.outcome, event.timeline, event.turnId);
      // Not awaited: turn-end recovery never waits for, or fails with, a Lead replacement.
      runtime.succession.onTurnEnded(event.agent.id).catch((error: unknown) => {
        console.error(`[paseo-room-runtime] Reading a handoff failed: ${error instanceof Error ? error.message : String(error)}`);
      });
    },
    permissionRequested: async event => {
      await runtime.turns.permissionRequested(event);
      await attention.onPermissionRequested(event.agent.id, event.request.id);
    },
    permissionResolved: async event => {
      await runtime.turns.permissionResolved(event);
      await retryHeld(event.agent.id);
      await attention.onPermissionResolved(event.agent.id, event.requestId);
    },
  }));
  attention.startTimer();
  return () => {
    for (const dispose of disposers) dispose();
    attention.dispose();
    runtime.spool.stop();
    runtime.handle.clear();
  };
}
