/**
 * Server entry of the paseo-room runtime coordination plugin (preview).
 *
 * Paseo compiles this directory as-is. Only host-supplied modules may be imported —
 * `@getpaseo/plugin*` and `zod` — because the installed plugin has no `node_modules`.
 * See docs/design/runtime-coordination.md §3.3 for the components this entry registers.
 */
import type { PluginServerContribution } from '@getpaseo/plugin/server';
import { createRuntimeContext } from './server/context.js';
import { ROOM_LOCATION } from './server/generated/location.js';
import { handleSessionOpen, transformAgentCreate } from './server/hooks.js';
import { registerLifecycle } from './server/lifecycle.js';
import { registerRpcs } from './server/rpc.js';

const contribute: PluginServerContribution = server => {
  if (ROOM_LOCATION === undefined) {
    console.error('[paseo-room-runtime] This plugin was not generated by paseo-room setup; the runtime stays inactive.');
    return () => undefined;
  }
  const runtime = createRuntimeContext(ROOM_LOCATION);
  runtime.start().catch((error: unknown) => {
    console.error(`[paseo-room-runtime] The runtime could not start: ${error instanceof Error ? error.message : String(error)}`);
  });
  const disposers = [
    server.before('agent.create', async ({ request }, context) => {
      runtime.handle.supply(context.paseo);
      await runtime.ready;
      return transformAgentCreate(request, runtime.hooks);
    }),
    server.before('agent.session_open', async ({ request }, context) => {
      runtime.handle.supply(context.paseo);
      await runtime.ready;
      const outcome = await handleSessionOpen(request, runtime.hooks);
      if (outcome === 'ambiguous' || outcome === 'provider-mismatch') {
        console.error(`[paseo-room-runtime] Correlation for agent ${request.agentId} is ${outcome}; it will not be trusted.`);
      }
      return undefined;
    }),
  ];
  registerRpcs(server, runtime);
  disposers.push(registerLifecycle(server, runtime.handle, runtime.recovery, {
    turnEnded: async event => { await runtime.turns.turnEnded(event); },
    permissionRequested: async event => { await runtime.turns.permissionRequested(event); },
    permissionResolved: async event => { await runtime.turns.permissionResolved(event); },
  }));
  return () => {
    for (const dispose of disposers) dispose();
    runtime.spool.stop();
    runtime.handle.clear();
  };
};

export default contribute;
