/**
 * Server entry of the paseo-room runtime coordination plugin (preview).
 *
 * Paseo compiles this directory as-is. Only host-supplied modules may be imported —
 * `@getpaseo/plugin*` and `zod` — because the installed plugin has no `node_modules`.
 * See docs/design/runtime-coordination.md §3.3 for the components this entry registers.
 */
import type { PluginServerContext } from '@getpaseo/plugin/server';
import { ATTENTION_SETTINGS } from './shared/attention.js';
import { PEER_EFFORT_SETTINGS } from './shared/effort.js';
import { createRuntimeContext } from './server/context.js';
import { ROOM_LOCATION } from './server/generated/location.js';
import { handleSessionOpen, transformAgentCreate } from './server/hooks.js';
import { registerLifecycle } from './server/lifecycle.js';
import { registerRpcs } from './server/rpc.js';

// A hoisted function declaration on purpose: Paseo copies the bundle's exports eagerly before a
// `const` initializer would run, so a `const contribute` default export reaches it as undefined.
export default function contribute(server: PluginServerContext): () => void {
  if (ROOM_LOCATION === undefined) {
    console.error('[paseo-room-runtime] This plugin was not generated by paseo-room setup; the runtime stays inactive.');
    return () => undefined;
  }
  const runtime = createRuntimeContext(ROOM_LOCATION);
  runtime.start().catch((error: unknown) => {
    console.error(`[paseo-room-runtime] The runtime could not start: ${error instanceof Error ? error.message : String(error)}`);
  });
  const disposers = [
    server.before('agent.create', async ({ request }, context) => {
      runtime.handle.supply(context.paseo);
      await runtime.ready;
      return transformAgentCreate(request, runtime.hooks);
    }),
    server.before('agent.session_open', async ({ request }, context) => {
      runtime.handle.supply(context.paseo);
      await runtime.ready;
      const outcome = await handleSessionOpen(request, runtime.hooks);
      if (outcome === 'ambiguous' || outcome === 'provider-mismatch') {
        console.error(`[paseo-room-runtime] Correlation for agent ${request.agentId} is ${outcome}; it will not be trusted.`);
      }
      return undefined;
    }),
  ];
  registerRpcs(server, runtime);
  // Room attention settings live in Paseo's host settings store. Without one (no settings
  // directory), the runtime keeps the defaults and the settings screen says so.
  try {
    const settings = server.registerSettings(ATTENTION_SETTINGS);
    runtime.attentionSettings.available = true;
    const adopt = (state: Awaited<ReturnType<typeof settings.read>>): void => {
      if (state.status === 'ready') runtime.attentionSettings.current = state.values;
    };
    settings.read().then(adopt, () => undefined);
    const unsubscribe = settings.subscribe(adopt);
    disposers.push(() => { void unsubscribe(); });
  } catch (error) {
    console.error(`[paseo-room-runtime] Room attention settings are unavailable; defaults apply: ${error instanceof Error ? error.message : String(error)}`);
  }
  // The Peer thinking envelope lives in the same store; without one, Peers keep their profile default.
  try {
    const effort = server.registerSettings(PEER_EFFORT_SETTINGS);
    runtime.peerEffort.available = true;
    const adopt = (state: Awaited<ReturnType<typeof effort.read>>): void => {
      if (state.status !== 'ready') return;
      runtime.adoptPeerEffort(state.values).catch((error: unknown) => {
        console.error(`[paseo-room-runtime] The Lead tool list could not be rewritten: ${error instanceof Error ? error.message : String(error)}`);
      });
    };
    effort.read().then(adopt, () => undefined);
    const unsubscribe = effort.subscribe(adopt);
    disposers.push(() => { void unsubscribe(); });
  } catch (error) {
    console.error(`[paseo-room-runtime] Peer effort settings are unavailable; profile defaults apply: ${error instanceof Error ? error.message : String(error)}`);
  }
  // A notice held for a recipient's pending permission is retried once that agent can take it.
  const retryHeld = (agentId: string): Promise<number> => runtime.controller.notices.retryFor(agentId);
  const { attention } = runtime;
  disposers.push(registerLifecycle(server, runtime.handle, runtime.recovery, {
    created: async event => { await attention.onCreated(event.agent.id); },
    turnStarted: async event => { await attention.onTurnStarted(event.agent.id); },
    archived: async event => { await attention.onArchived(event.agent.id, event.archivedAt); },
    turnEnded: async event => {
      await runtime.turns.turnEnded(event);
      await retryHeld(event.agent.id);
      await attention.onTurnEnded(event.agent.id, event.outcome, event.timeline, event.turnId);
    },
    permissionRequested: async event => {
      await runtime.turns.permissionRequested(event);
      await attention.onPermissionRequested(event.agent.id, event.request.id);
    },
    permissionResolved: async event => {
      await runtime.turns.permissionResolved(event);
      await retryHeld(event.agent.id);
      await attention.onPermissionResolved(event.agent.id, event.requestId);
    },
  }));
  attention.startTimer();
  return () => {
    for (const dispose of disposers) dispose();
    attention.dispose();
    runtime.spool.stop();
    runtime.handle.clear();
  };
}
