import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Entry } from './fsops.js';
import type { Layout } from './layout.js';
import { providerId, type Role } from './roles.js';
import { contractDigest, renderInstructions } from './room/instructions.js';

export const CLAUDE_CARRIER_PLUGIN_ID = 'paseo-room-claude-carrier';
export const CLAUDE_CARRIER_PASEO_RANGE = '>=0.8.0 <0.9.0';

const STATIC_ASSETS = [
  'paseo-plugin.json',
  'package.json',
  'tsconfig.json',
  'index.server.ts',
  'server/carrier.ts',
] as const;

function loadAsset(path: string): string {
  return readFileSync(new URL(`./plugin-assets/${path}`, import.meta.url), 'utf8');
}

export function claudeCarrierPluginDir(layout: Layout): string {
  return join(layout.roomHome, 'plugin');
}

export function renderClaudeCarrierContract(roles: readonly Role[]): string {
  const contracts = Object.fromEntries(roles.map(role => [providerId('claude', role), renderInstructions(role)]));
  return [
    '/** Generated by paseo-room. The Markdown prompt assets remain authoritative. */',
    `export const GENERATION = ${JSON.stringify(contractDigest())};`,
    `export const CONTRACT: Readonly<Record<string, string>> = ${JSON.stringify(contracts, null, 2)};`,
    '',
  ].join('\n');
}

export function claudeCarrierEntries(layout: Layout, roles: readonly Role[]): Entry[] {
  const root = claudeCarrierPluginDir(layout);
  return [
    { kind: 'dir', path: root },
    { kind: 'dir', path: join(root, 'server') },
    ...STATIC_ASSETS.map(path => ({ kind: 'file' as const, path: join(root, path), content: loadAsset(path) })),
    { kind: 'file', path: join(root, 'server', 'contract.ts'), content: renderClaudeCarrierContract(roles) },
  ];
}
