import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Entry } from './fsops.js';
import type { Layout } from './layout.js';
import { providerId, ROLE_PEER_REPORTING, type AgentId, type Role } from './roles.js';
import { contractDigest } from './room/instructions.js';
import { MANIFEST_FILE, runtimeRoomManifestSchema, type RuntimeRoomManifestV1 } from './runtime-plugin/shared/manifest.js';
import { RUNTIME_PASEO_RANGE, RUNTIME_PLUGIN_ID } from './runtime-plugin/shared/identity.js';
import { runtimeRolePolicy } from './runtime-plugin/shared/policy.js';

export { RUNTIME_PASEO_RANGE, RUNTIME_PLUGIN_ID };

/** The bundled plugin tree: `src/runtime-plugin` in a checkout, `dist/runtime-plugin` when packed. */
const BUNDLE = fileURLToPath(new URL('./runtime-plugin/', import.meta.url));

export function runtimePluginDir(layout: Layout): string {
  return join(layout.roomHome, 'runtime-plugin');
}

function digest(value: unknown): string {
  return `sha256:${createHash('sha256').update(JSON.stringify(value)).digest('hex').slice(0, 16)}`;
}

/** Every role's runtime policy, as the canonical reporting policy decides it. */
function reportingPolicy(): Record<Role, ReturnType<typeof runtimeRolePolicy>> {
  return {
    supervisor: runtimeRolePolicy('supervisor', ROLE_PEER_REPORTING.supervisor),
    lead: runtimeRolePolicy('lead', ROLE_PEER_REPORTING.lead),
    peer: runtimeRolePolicy('peer', ROLE_PEER_REPORTING.peer),
  };
}

/** Changes exactly when the approved reporting policy changes, so a stale plugin can refuse it. */
export function reportingPolicyGeneration(): string {
  return digest(reportingPolicy());
}

/**
 * The generated room manifest: exact provider ids mapped to role capabilities, with
 * `peerReporting` only where `ROLE_PEER_REPORTING` allows it. Deterministic, so rerunning setup
 * shows no phantom change, and validated against the plugin's own strict schema before use.
 */
export function renderRuntimeManifest(agents: readonly AgentId[], roles: readonly Role[]): RuntimeRoomManifestV1 {
  const policy = reportingPolicy();
  const providers: RuntimeRoomManifestV1['providers'] = {};
  for (const agent of agents) {
    for (const role of roles) {
      const { capabilities, peerReporting } = policy[role];
      providers[providerId(agent, role)] = {
        agent, role, capabilities: [...capabilities],
        ...(peerReporting === undefined ? {} : { peerReporting: { ...peerReporting, tools: ['ask', 'handoff'] } }),
      };
    }
  }
  const contractGeneration = contractDigest();
  return runtimeRoomManifestSchema.parse({
    schema: 1,
    roomGeneration: digest({ agents: [...agents], roles: [...roles], contractGeneration }),
    contractGeneration,
    reportingPolicyGeneration: reportingPolicyGeneration(),
    providers,
  });
}

export function renderRuntimeManifestFile(agents: readonly AgentId[], roles: readonly Role[]): string {
  return `${JSON.stringify(renderRuntimeManifest(agents, roles), null, 2)}\n`;
}

export const LOCATION_MODULE = 'server/generated/location.ts';

/** The per-room locator the plugin reads, since Paseo evaluates it without a file path of its own. */
export function renderRuntimeLocation(layout: Layout): string {
  const location = { pluginDirectory: runtimePluginDir(layout), runtimeRoot: join(layout.roomHome, 'runtime', 'v1') };
  return [
    '/** Generated by paseo-room setup for this room. */',
    'export interface RoomLocation {',
    '  readonly pluginDirectory: string;',
    '  readonly runtimeRoot: string;',
    '}',
    '',
    `export const ROOM_LOCATION: RoomLocation | undefined = ${JSON.stringify(location)};`,
    '',
  ].join('\n');
}

/** Relative paths of the bundled plugin tree, directories first so they are planned before files. */
function bundleInventory(): { readonly dirs: string[]; readonly files: string[] } {
  const entries = readdirSync(BUNDLE, { recursive: true, withFileTypes: true });
  const toRelative = (entry: (typeof entries)[number]): string =>
    relative(BUNDLE, join(entry.parentPath, entry.name)).split(sep).join('/');
  return {
    dirs: entries.filter(entry => entry.isDirectory()).map(toRelative).sort(),
    files: entries.filter(entry => entry.isFile()).map(toRelative).sort(),
  };
}

/**
 * The runtime plugin as ordinary managed entries under `~/.paseo-room/runtime-plugin`. The
 * plugin-owned `~/.paseo-room/runtime` state tree is deliberately absent: setup never plans,
 * compares, replaces or deletes it.
 */
export function runtimePluginEntries(layout: Layout, agents: readonly AgentId[], roles: readonly Role[]): Entry[] {
  const root = runtimePluginDir(layout);
  const { dirs, files } = bundleInventory();
  const generatedDir = MANIFEST_FILE.split('/').slice(0, -1).join('/');
  return [
    { kind: 'dir', path: root },
    ...[...new Set([...dirs, generatedDir])].sort().map(path => ({ kind: 'dir' as const, path: join(root, path) })),
    ...files.map(path => ({
      kind: 'file' as const, path: join(root, path),
      content: path === LOCATION_MODULE ? renderRuntimeLocation(layout) : readFileSync(join(BUNDLE, path), 'utf8'),
    })),
    { kind: 'file', path: join(root, MANIFEST_FILE), content: renderRuntimeManifestFile(agents, roles) },
  ];
}
